name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - dst
          - int
          - prod
      folder:
        description: 'Folder to deploy'
        required: true
        default: 'notebook'
        type: choice
        options:
          - notebook
          - src

jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload folder to S3
        run: |
          FOLDER=${{ github.event.inputs.folder }}
          ENV=${{ github.event.inputs.environment }}
          S3_PATH="s3://$S3_BUCKET_NAME/$ENV/$FOLDER/"

          echo "Uploading $FOLDER to $S3_PATH"
          aws s3 cp $FOLDER $S3_PATH --recursive
